**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

In [27]:
arr = np.random.randint(1, 100, (4, 6))
arr

array([[98, 86, 33, 55, 49, 14],
       [27, 20, 78, 94, 36,  9],
       [46, 38, 60, 37, 86, 80],
       [16, 93, 79, 29, 49, 22]], dtype=int32)

In [41]:
np.array([1, 2, 3], dtype=np.float32)[::-1]

array([3., 2., 1.], dtype=float32)

In [ ]:
# Print every second element from each row of the array `arr`
arr[:,::2]

array([[98, 33, 49],
       [27, 78, 36],
       [46, 60, 86],
       [16, 79, 49]], dtype=int32)

##### `Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [3]:
#Code here
a1 = np.nan*np.empty(10)

a1[4]= 1

a1

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

##### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
x = int(input("Enter a number: "))
y = int(input("Enter another number: "))
print(f"The first number is {x} and the another number is {y}")

# x,y = map(int, input("Enter two numbers: ").split())

n = np.random.random((x,y))
print(n)
print(n.mean())

The first number is 4 and the another number is 5
[[0.94933299 0.83806624 0.6614342  0.04285124 0.96832196]
 [0.56878871 0.55296574 0.84171307 0.70522916 0.6812428 ]
 [0.03138769 0.80167885 0.9029031  0.60076333 0.29946886]
 [0.97564522 0.27797653 0.96471593 0.82691187 0.6723667 ]]
0.6581882083642796


##### `Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [3]:
def border_array(a,b):
    arr = np.ones((a,b))
    arr[1:-1,1:-1] = 0
    return arr

print(border_array(3,4))

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [7]:
print(np.linspace(0,1,12)[1:-1])

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


##### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
# Identity matricx is a square mattrix, means no of rows and columns will always be same.
# Here shape given 3,4 so identuty matrix not possible.

#Identy matrix of size 3-- 3X3
np.eye(3)

#Identy matrix of size 4-- 4X4
np.identity(4)

# eye and identity are same.

##### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [8]:
z = np.zeros((5,5))
z+= np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [ ]:
# Alternative way to create the same matrix
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

# matrix = np.array([np.arange(5)] * 5)
# print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


##### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
a = np.random.randint(1, 100, (10, 2))
p = np.array([2,3])
np.sqrt(np.sum((a-p)**2, axis=1)).astype(int)

array([123,  45,  75,  92,  36,  71, 107,  75,  81, 120])

In [28]:
# Step 1: Generate random integer coordinates
coords = np.random.randint(1, 101, size=(10, 2))

# Step 2: Given point
point = np.array([2, 3])

# Step 3: Compute Euclidean distance from the point
distances = np.sqrt(np.sum((coords - point) ** 2, axis=1))

# Step 4: Convert to integer type
distances = distances.astype(int)

# Step 5: Display results
print("Coordinates:\n", coords)
print("\nDistances:\n", distances)


Coordinates:
 [[ 25  75]
 [ 32  16]
 [ 53  63]
 [100  46]
 [  3  64]
 [ 53  90]
 [ 28  46]
 [ 37  12]
 [ 63  77]
 [ 69  60]]

Distances:
 [ 75  32  78 107  61 100  50  36  95  87]


##### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [27]:
np.unravel_index(100, (6,7,8))

(np.int64(1), np.int64(5), np.int64(4))

In [ ]:
tuple(map(int, np.unravel_index(100, (6, 7, 8))))


(1, 5, 4)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [36]:
a = input("Enter the desired numbers with space separated: ").strip().split()
print(a)
np.array(a[::-1], dtype=np.float32)

['2', '-7', '8', '9', '0', '-4']


array([-4.,  0.,  9.,  8., -7.,  2.], dtype=float32)

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [43]:
a = np.array([])
a = np.array([1, 2])
# a = np.zeros((2,3))
a.size


2

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [45]:
def softmax(arr):
    if type(arr) != np.ndarray:
        raise TypeError("Requires Numpy Array")
    elif arr.ndim > 1:
        raise TypeError("Requires 1D Array")
    s = np.sum(np.exp(arr))
    return np.exp(arr)/s

softmax(np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318]))

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [46]:
def vertical_stack(*args):
    for i in args:
        if type(i) != np.ndarray:
            raise TypeError("Requires Numpy Array")
    return np.vstack(args)

a = np.arange(10).reshape(2, -1)
print("a=",a)

b = np.repeat(1, 10).reshape(2, -1)
print("b=",b)

print(vertical_stack(a,b))

c = np.random.random((2,5))
print("c=", c)

vertical_stack(a,b,c)

a= [[0 1 2 3 4]
 [5 6 7 8 9]]
b= [[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
c= [[0.08046118 0.05618659 0.6759575  0.46829025 0.38340695]
 [0.88252428 0.53036782 0.35842973 0.65976214 0.54512176]]


array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.08046118, 0.05618659, 0.6759575 , 0.46829025, 0.38340695],
       [0.88252428, 0.53036782, 0.35842973, 0.65976214, 0.54512176]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [4]:
def date_array():
    return np.arange('2023-01-01', '2023-02-01', dtype='datetime64[D]')

date_array()

array(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
       '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
       '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
       '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
       '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
       '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
       '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
       '2023-01-29', '2023-01-30', '2023-01-31'], dtype='datetime64[D]')

In [ ]:
# CampusX Task 13 NumPy-1
def date_array(start: str, end: str):
    if type(start) != str or type(end) != str:
        raise TypeError
        
    total_days_of_month = {"01": 31, "02": 28, "03": 31, "04":30, "05": 31, "06":30, "07":31, "08":31, "09":30, "10": 31, "11":30, "12":31}

    end = end.split("-")
    end_last = int(end[-1]) + 1
    
    # If the next day of end falls in the next month, account for that
    if total_days_of_month[end[-2]] < end_last:
        days_diff = end_last - total_days_of_month[end[-2]]
        end[-1] = f'0{days_diff}' if days_diff< 10 else f'{days_diff}'
        next_month = int(end[-2]) + 1
        end[-2] = f'0{next_month}' if next_month< 10 else f'{next_month}'
    else:
        end[-1] = f'0{end_last}' if end_last < 10 else f'{end_last}'
    end = "-".join(end)
    return np.arange(start, end, dtype="datetime64[D]")    # Use arange() to generate all dates between start and end 
date_array(start = '2020-11-25', end = '2020-12-05')

array(['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
       '2020-11-29', '2020-11-30', '2020-12-01', '2020-12-02',
       '2020-12-03', '2020-12-04', '2020-12-05'], dtype='datetime64[D]')

In [12]:
# --- New function with parameters ---

def date_array(start_date, end_date):
    # --- Validation ---
    if not (isinstance(start_date, str) and isinstance(end_date, str)):
        raise TypeError("Both inputs must be strings in 'YYYY-MM-D' format.")
    
    # --- Convert to numpy datetime64 ---
    try:
        start = np.datetime64(start_date)
        end = np.datetime64(end_date)
    except Exception:
        raise ValueError("Dates must be in 'YYYY-MM-D' format, e.g. '2022-12-6'.")
    
    # --- Ensure same year ---
    if str(start)[:4] != str(end)[:4]:
        raise ValueError("Both dates must be from the same year.")
    
    # --- Generate date range (inclusive) ---
    dates = np.arange(start, end + np.timedelta64(1, 'D'), dtype='datetime64[D]')
    
    return dates

date_array('2023-01-01', '2023-01-31')


array(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
       '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
       '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
       '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
       '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
       '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
       '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
       '2023-01-29', '2023-01-30', '2023-01-31'], dtype='datetime64[D]')

##### `Q-14:` Subtract the mean of each row from a matrix.

In [47]:
x = np.random.random((3,2))
x-x.mean(axis=1, keepdims=True)

array([[-0.06689688,  0.06689688],
       [ 0.16209184, -0.16209184],
       [ 0.16643906, -0.16643906]])

In [19]:

# Example matrix
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Compute mean of each row (axis=1)
row_means = arr.mean(axis=1, keepdims=True)

# Subtract row means from each element
result = arr - row_means

print(result)



# Calculate mean of each column
col_means = arr.mean(axis=0, keepdims=True)

# Subtract column means from each element
result = arr - col_means

print("subtract column means from each element:  \n", result)


[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
subtract column means from each element:  
 [[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]


##### `Q-15:` Swap column-1 of array with column-2 in the array.

In [57]:
array = np.arange(9).reshape(3,3)
array


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
array[:, [0, 2, 1]]
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### `Q-16:` Replace odd elements in arrays with -1.

In [59]:
a = np.arange(10)
a[a%2 == 1] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

##### `Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [60]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

a[b>a] = b[a<b]
a

array([6, 3, 1, 7, 8])

##### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [30]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[4543,  940, 5951,   37,  332],
       [3669,  547, 4285, 9966, 5430],
       [3526, 2274, 7349, 3434, 3783],
       [5502, 5845, 3112, 3975, 5380],
       [3673, 4446, 6002, 6501, 5339],
       [7608, 8494, 8304, 5571, 7948],
       [9595, 6356, 2622, 6099, 2441],
       [9975,  936, 6881, 4677, 2868]], dtype=int32)

In [31]:
# Question Part 1:

arr1[:,::2]

array([[4543, 5951,  332],
       [3669, 4285, 5430],
       [3526, 7349, 3783],
       [5502, 3112, 5380],
       [3673, 6002, 5339],
       [7608, 8304, 7948],
       [9595, 2622, 2441],
       [9975, 6881, 2868]], dtype=int32)

In [32]:
(arr1 - arr1.min())/(arr1.max() - arr1.min())

array([[0.45341115, 0.09086335, 0.59508956, 0.        , 0.02968404],
       [0.36546589, 0.05131817, 0.42745019, 0.99909439, 0.54266452],
       [0.35107668, 0.22509559, 0.73576172, 0.34181928, 0.37693701],
       [0.54990944, 0.58442343, 0.30941839, 0.39625679, 0.53763333],
       [0.36586838, 0.44365063, 0.60022137, 0.65043268, 0.53350775],
       [0.7618233 , 0.85097605, 0.83185752, 0.55685249, 0.79603542],
       [0.96176293, 0.63584222, 0.2601127 , 0.60998189, 0.24189978],
       [1.        , 0.09046086, 0.68866975, 0.46689475, 0.28486617]])

##### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [40]:
def nthmax(arr,n):
    if type(arr) != np.ndarray:
        raise TypeError("Requires Numpy Array")
    elif arr.ndim > 1:
        raise TypeError("Requires 1D Array")
    elif n > arr.size:
        raise ValueError("n should be less than or equal to the size of the array")
    
    sorted_unique = np.unique(np.sort(arr))
    return sorted_unique[-n]

nthmax(np.array([1,2,3,4,5,6,7,8,9,10]), 3)

np.int64(8)

##### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [41]:
a = np.array([1,2,3])
np.hstack([np.repeat(a, 3), np.tile(a, 3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])