**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [2]:
import numpy as np

In [22]:
np.random.randint(1, 100, (4, 2))

array([[56, 76],
       [37, 17],
       [61, 46],
       [ 8, 36]], dtype=int32)

In [41]:
np.array([1, 2, 3], dtype=np.float32)[::-1]

array([3., 2., 1.], dtype=float32)

##### `Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [3]:
#Code here
a1 = np.nan*np.empty(10)

a1[4]= 1

a1

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

##### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
x = int(input("Enter a number: "))
y = int(input("Enter another number: "))
print(f"The first number is {x} and the another number is {y}")

# x,y = map(int, input("Enter two numbers: ").split())

n = np.random.random((x,y))
print(n)
print(n.mean())

The first number is 4 and the another number is 5
[[0.94933299 0.83806624 0.6614342  0.04285124 0.96832196]
 [0.56878871 0.55296574 0.84171307 0.70522916 0.6812428 ]
 [0.03138769 0.80167885 0.9029031  0.60076333 0.29946886]
 [0.97564522 0.27797653 0.96471593 0.82691187 0.6723667 ]]
0.6581882083642796


##### `Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [3]:
def border_array(a,b):
    arr = np.ones((a,b))
    arr[1:-1,1:-1] = 0
    return arr

print(border_array(3,4))

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [7]:
print(np.linspace(0,1,12)[1:-1])

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


##### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
# Identity matricx is a square mattrix, means no of rows and columns will always be same.
# Here shape given 3,4 so identuty matrix not possible.

#Identy matrix of size 3-- 3X3
np.eye(3)

#Identy matrix of size 4-- 4X4
np.identity(4)

# eye and identity are same.

##### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [8]:
z = np.zeros((5,5))
z+= np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [ ]:
# Alternative way to create the same matrix
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

# matrix = np.array([np.arange(5)] * 5)
# print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


##### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
a = np.random.randint(1, 100, (10, 2))
p = np.array([2,3])
np.sqrt(np.sum((a-p)**2, axis=1)).astype(int)

array([123,  45,  75,  92,  36,  71, 107,  75,  81, 120])

In [28]:
# Step 1: Generate random integer coordinates
coords = np.random.randint(1, 101, size=(10, 2))

# Step 2: Given point
point = np.array([2, 3])

# Step 3: Compute Euclidean distance from the point
distances = np.sqrt(np.sum((coords - point) ** 2, axis=1))

# Step 4: Convert to integer type
distances = distances.astype(int)

# Step 5: Display results
print("Coordinates:\n", coords)
print("\nDistances:\n", distances)


Coordinates:
 [[ 25  75]
 [ 32  16]
 [ 53  63]
 [100  46]
 [  3  64]
 [ 53  90]
 [ 28  46]
 [ 37  12]
 [ 63  77]
 [ 69  60]]

Distances:
 [ 75  32  78 107  61 100  50  36  95  87]


##### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [27]:
np.unravel_index(100, (6,7,8))

(np.int64(1), np.int64(5), np.int64(4))

In [ ]:
tuple(map(int, np.unravel_index(100, (6, 7, 8))))


(1, 5, 4)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [36]:
a = input("Enter the desired numbers with space separated: ").strip().split()
print(a)
np.array(a[::-1], dtype=np.float32)

['2', '-7', '8', '9', '0', '-4']


array([-4.,  0.,  9.,  8., -7.,  2.], dtype=float32)

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [43]:
a = np.array([])
a = np.array([1, 2])
# a = np.zeros((2,3))
a.size


2

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [45]:
def softmax(arr):
    if type(arr) != np.ndarray:
        raise TypeError("Requires Numpy Array")
    elif arr.ndim > 1:
        raise TypeError("Requires 1D Array")
    s = np.sum(np.exp(arr))
    return np.exp(arr)/s

softmax(np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318]))

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [46]:
def vertical_stack(*args):
    for i in args:
        if type(i) != np.ndarray:
            raise TypeError("Requires Numpy Array")
    return np.vstack(args)

a = np.arange(10).reshape(2, -1)
print("a=",a)

b = np.repeat(1, 10).reshape(2, -1)
print("b=",b)

print(vertical_stack(a,b))

c = np.random.random((2,5))
print("c=", c)

vertical_stack(a,b,c)

a= [[0 1 2 3 4]
 [5 6 7 8 9]]
b= [[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
c= [[0.08046118 0.05618659 0.6759575  0.46829025 0.38340695]
 [0.88252428 0.53036782 0.35842973 0.65976214 0.54512176]]


array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.08046118, 0.05618659, 0.6759575 , 0.46829025, 0.38340695],
       [0.88252428, 0.53036782, 0.35842973, 0.65976214, 0.54512176]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here

##### `Q-14:` Subtract the mean of each row from a matrix.

In [47]:
x = np.random.random((3,2))
x-x.mean(axis=1, keepdims=True)

array([[-0.06689688,  0.06689688],
       [ 0.16209184, -0.16209184],
       [ 0.16643906, -0.16643906]])

##### `Q-15:` Swap column-1 of array with column-2 in the array.

In [57]:
array = np.arange(9).reshape(3,3)
array


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
array[:, [0, 2, 1]]
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### `Q-16:` Replace odd elements in arrays with -1.

In [59]:
a = np.arange(10)
a[a%2 == 1] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

##### `Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [60]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

a[b>a] = b[a<b]
a

array([6, 3, 1, 7, 8])

##### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[2939, 1694, 6680, 8865, 2684],
       [4066, 4573,  327, 6525,  851],
       [5997, 7481, 2315, 5863, 9615],
       [7821, 1225, 9138, 1114, 4885],
       [7715, 8046, 9105, 3935, 3182],
       [8842, 4836, 2705, 3751, 3800],
       [4132, 1400, 7844, 9471, 7526],
       [2749, 2624, 6900, 1576, 7515]])

In [ ]:
#Code here

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [ ]:
#Code here

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
#code here