In [2]:
import numpy as np

In [ ]:
# axis = 1 for row-wise operation
# axis = 0 for column-wise operation

#### `Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [10]:
arr = np.random.randint(1, 100, (4, 3))
arr

array([[30, 74, 63],
       [38, 26,  2],
       [47, 66, 77],
       [50, 21, 66]], dtype=int32)

In [12]:

arr_sorted = np.sort(arr)
arr_sorted

array([[30, 63, 74],
       [ 2, 26, 38],
       [47, 66, 77],
       [21, 50, 66]], dtype=int32)

In [11]:
arr_sorted_col2 = arr[arr[:,1].argsort()]
arr_sorted_col2

array([[50, 21, 66],
       [38, 26,  2],
       [47, 66, 77],
       [30, 74, 63]], dtype=int32)

In [22]:
arr_row_max = np.array(sorted(arr, key = lambda x: max(x)))
arr_row_max

array([[38, 26,  2],
       [50, 21, 66],
       [30, 74, 63],
       [47, 66, 77]], dtype=int32)

In [23]:
arr_elt= np.sort(arr, axis = None).reshape(4,3)
arr_elt

array([[ 2, 21, 26],
       [30, 38, 47],
       [50, 63, 66],
       [66, 74, 77]], dtype=int32)

#### `Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [10]:
# code here
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])



In [13]:
extra_subject = np.array([41, 87, 72, 36, 92]).reshape(-1, 1)
print(extra_subject)
marks = np.concatenate([marks, extra_subject], axis = 1)
print("Marks of students \n",marks)

[[41]
 [87]
 [72]
 [36]
 [92]]
Marks of students 
 [[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]


In [14]:
rec1 = np.array([77, 83, 98, 95, 89]).reshape(1, -1)
rec2 = np.array([92, 71, 52, 61, 53]).reshape(1, -1)
marks = np.concatenate([marks, rec1, rec2], axis = 0)
print("Marks of students \n",marks)

Marks of students 
 [[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]
 [77 83 98 95 89]
 [92 71 52 61 53]]


In [17]:
sum_of_marks = np.sum(marks, axis = 1, keepdims = True)
print("Sum of marks \n", sum_of_marks)
marks = np.concatenate([marks, sum_of_marks], axis = 1)
print("Marks of students \n",marks)

Sum of marks 
 [[106]
 [328]
 [229]
 [234]
 [315]
 [442]
 [329]]
Marks of students 
 [[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]


In [18]:
print(np.array(sorted(marks, key = lambda x: x[-1], reverse=True)))

[[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]
 [ 63  46  90  42  87 328]
 [ 67  61  59  36  92 315]
 [ 82   9  29  78  36 234]
 [ 39  76  13  29  72 229]
 [ 13  10   9  33  41 106]]


##### `Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [19]:
# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
#1
print(np.unique(arr, axis = 0))
#2
print(np.unique(arr, axis = 1))

[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


##### `Q-4:` Flip given 2-D array along both axes at the same time.

In [20]:
# code here
arr = np.array([[1,2,3,3,1,1],
               [0,9,1,2,8,8],
               [1,2,3,8,8,8],
               [1,2,3,3,1,1],
               [0,6,1,2,11,7],
               [10,19,14,-2,8,-1]])
np.flip(arr, axis = [0, 1])

array([[-1,  8, -2, 14, 19, 10],
       [ 7, 11,  2,  1,  6,  0],
       [ 1,  1,  3,  3,  2,  1],
       [ 8,  8,  8,  3,  2,  1],
       [ 8,  8,  2,  1,  9,  0],
       [ 1,  1,  3,  3,  2,  1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [24]:
# code here
arr = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])

X = 6
# np.where(np.array(arr) < X, 'yes', 'no')
np.where(np.any(arr > X, axis = 1))

(array([1, 3]),)

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [26]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [27]:
# code here
np.concatenate([arr1, arr2, arr3])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [28]:
# code here
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
print(arr)

max_element = arr.argmax()
min_element = arr.argmin()
print(arr.max(), arr.min())

arr = np.delete(arr, max_element, axis = 1)
arr = np.delete(arr, min_element, axis = 1)

print(arr.max(), arr.min())

[[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
  181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
  353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
  921 490 527 972 278 307 840 958 246 449 251 957 103 627 920 824 356 825
  173 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211
  771 270 308 231 952 514 699 702 433 900 373 318 998 265 503 320 230 324
  922 967 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930
  325 729 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528
  395 525 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859
  618 226 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748
  291 194 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207
  883 588]]
998 103
997 117


### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [32]:
# # code here
# arr = np.random.randint(0, 200, 50)
# np.cumsum(np.sort(np.clip(arr, 100, 200)))


# Step 1: Create a random array in [100, 700]
arr = np.random.randint(100, 701, size=10)
print("Original array:", arr)

# Step 2: Limit values between 100 and 200
arr = np.clip(arr, 100, 200)
print("Clipped array:", arr)

# Step 3: Sort the array
arr_sorted = np.sort(arr)
print("Sorted array:", arr_sorted)

# Step 4: Cumulative sum
cumsum_arr = np.cumsum(arr_sorted)
print("Cumulative sum:", cumsum_arr)


Original array: [648 226 104 647 159 483 236 420 676 449]
Clipped array: [200 200 104 200 159 200 200 200 200 200]
Sorted array: [104 159 200 200 200 200 200 200 200 200]
Cumulative sum: [ 104  263  463  663  863 1063 1263 1463 1663 1863]


### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [33]:
# code here
arr = np.random.random(100)
arr = np.around(arr, decimals = 3)

print("0th percentile == minimum value of the array: ", (np.percentile(arr, 0) == arr.min()))
print("100th percentile == maximum value of the array: ", (np.percentile(arr, 100) == arr.max()))
print("difference betwen 51th percenile and 50th percentile values: ", (np.percentile(arr, 51) - np.percentile(arr, 50)))

0th percentile == minimum value of the array:  True
100th percentile == maximum value of the array:  True
difference betwen 51th percenile and 50th percentile values:  0.00492999999999999


In [34]:
# Step 1: Create a random array in range [0, 1]
arr = np.random.random(10)
print("Original array:\n", arr)

# Step 2: Round off to 3 decimal places
arr = np.round(arr, 3)
print("\nRounded array:\n", arr)

# Step 3: Calculate percentiles
p0 = np.percentile(arr, 0)
p100 = np.percentile(arr, 100)
p50 = np.percentile(arr, 50)
p51 = np.percentile(arr, 51)

# Step 4: Compare and find difference
print("\n0th percentile == min(arr)?", np.isclose(p0, np.min(arr)))
print("100th percentile == max(arr)?", np.isclose(p100, np.max(arr)))
print("\nDifference between 51st and 50th percentile:", p51 - p50)


Original array:
 [0.84685621 0.19763459 0.09416803 0.90107967 0.96297198 0.22351509
 0.552642   0.08316957 0.70331796 0.07359947]

Rounded array:
 [0.847 0.198 0.094 0.901 0.963 0.224 0.553 0.083 0.703 0.074]

0th percentile == min(arr)? True
100th percentile == max(arr)? True

Difference between 51st and 50th percentile: 0.02960999999999997
